# **데이터 다루기 복습**

## 0.환경준비 + 데이터 로드

* 라이브러리 불러오기

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

* 데이터 가져오기

In [4]:
sales = pd.read_csv("https://raw.githubusercontent.com/DA4BAM/dataset/master/sales.csv")
products = pd.read_csv("https://raw.githubusercontent.com/DA4BAM/dataset/master/products.csv")
# products.drop('CategoryOrd', axis =1, inplace = True)
customers = pd.read_csv("https://raw.githubusercontent.com/DA4BAM/dataset/master/customers2.csv")

In [6]:
sales.head()

   OrderID  Seq   OrderDate ProductID  Qty   Amt CustomerID
0      107    2  2016-01-02  p1036481    2  2100    c150417
1       69    1  2016-01-02  p1152861    1  1091    c212716
2       69    7  2016-01-02  p1013161    1  2600    c212716
3       69    8  2016-01-02  p1005771    1  1650    c212716
4       69   11  2016-01-02  p1089531    1  2600    c212716

In [8]:
products.head()

  ProductID ProductName Category SubCategory
0  p1052661         새우깡       간식          과자
1  p1054261       고구마스틱       간식          과자
2  p1097821          짱구       간식          과자
3  p1097831         감자칩       간식          과자
4  p1119071        뿌셔뿌셔       간식          과자

In [10]:
customers.head()

  CustomerID RegisterDate Gender  BirthYear
0    c328222   2014-09-25      F       1960
1    c281448   2013-06-18      F       1974
2    c038336   2003-10-10      F       1968
3    c084237   2007-03-09      F       1982
4    c162600   2010-06-14      F       1978

## 1.데이터프레임 조건 조회하기 : .loc

In [ ]:
# 1. 구매액(Amt)이 10000원 이상인 판매정보를 조회하시오.
# sales.loc[행 조건  , 열 이름]
# sales.loc[행 조건]

In [ ]:
# 2. 2016년 2월 판매 정보를 조회하시오.
# 조건 두개 이상 연결 &(and), |(or), 주의사항 : 조건 각각을 ()로 묶어야한다.

In [14]:
# 🤔3. 2번 문제를 .between()을 사용해서 조회해보세요.
sales.loc[sales['OrderDate'].between('2016-02-01', '2016-02-29')]

      OrderID  Seq   OrderDate ProductID  Qty    Amt CustomerID
4499      241    8  2016-02-01  p1012811    2   5000    c206248
4500      241    9  2016-02-01  p1012751    2   2700    c206248
4501      241   11  2016-02-01  p1144371    5  14250    c206248
4502      241   12  2016-02-01  p1179241    1   1500    c206248
4503      241   13  2016-02-01  p1013161    4  12000    c206248
...       ...  ...         ...       ...  ...    ...        ...
8851       25   11  2016-02-29  p1191881    1   1750    c146132
8852       25   12  2016-02-29  p1207281    1   2600    c146132
8853       25   14  2016-02-29  p1005621    1   2900    c146132
8854       25   19  2016-02-29  p1012751    1   1500    c146132
8855       27    1  2016-02-29  p1005621    1   2030    c146132

[4357 rows x 7 columns]

In [ ]:
sales.loc[sales['OrderDate'].between('2016-02-01', '2016-03-01', inclusive = 'left')]  #2월1일 부터 3월1일 전날까지!(왼쪽은 포함 오른쪽은 포함X)

* .between() : https://pandas.pydata.org/docs/reference/api/pandas.Series.between.html

In [ ]:
# 4. 상품들 중에서 하위 카테고리(SubCategory)가 사탕류, 과자, 빵 인 상품을 조회하시오. (.isin 사용)

* .isin() : https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isin.html

## 2.날짜 데이터 다루기

In [ ]:
# 1. Sales의 날짜 데이터를 날짜 형식으로 변환하시오.
# pd.to_datetime(date, format = '%d/%m/%Y') # format = '%d/%m/%Y' 입력되는 날짜가 이런 형태야~~ 라고 알려주는 옵션
# 날짜 타입으로 변환하면, 날짜 요소를 추출 할 수 있다.

* .to_datetime : https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html
* format : https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior

In [ ]:
# 2. sales 데이터프레임에 연도 변수를 추가하시오.
# 날짜형식의 변수.dt.  <==날짜 요소가 팝업으로...

In [ ]:
# 3. sales 데이터프레임에 월 변수를 추가하시오.

In [ ]:
# 4. customers 데이터프레임의 RegisterDate를 날짜타입으로 변환하시오.

In [ ]:
# 5. customers 데이터프레임에 다음 두 변수를 추가하시오.
# 등록연도 RegisterYear
# 등록기간(등록연도부터 현재까지의 년 수)

In [ ]:
# 6. customers 데이터프레임에 나이를 계산해서 변수를 추가하시오.
customers['Age'] = 2024 - customers['BirthYear']
customers.head()

In [ ]:
# 7. customers 데이터프레임에서 나이로 부터 연령대를 추가하시오. pd.cut
# 숫자형 변수를 범주로 변환해주기.

pd.cut 설명 (https://pandas.pydata.org/docs/reference/api/pandas.cut.html)

## 3.집계 : value_counts(), groupby()

* value_counts() : https://pandas.pydata.org/docs/reference/api/pandas.Series.value_counts.html
* groupby() : https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html

In [ ]:
# 1.Category 별 상품 수를 조회하시오.(.value_counts())

In [ ]:
# 2. 출생 연도별 회원수(.value_counts())

In [ ]:
# 3. 2016년 월별, 매출액과 총 판매수량(sum)을 조회. (.groupby)
# sales.head()
sales.loc[sales['Year']==2016].groupby('Month', as_index=False)[['Amt','Qty']].sum()

## 4.결합 ① : 조인 join(merge)

* 판다스에서 join은 굉장히 간단합니다.
* 자동으로 key를 잡아줍니다
* default로 inner join을 합니다.

In [22]:
# 🤔1. sales와 products를 ProductID 기준으로 merge하여 새로운 데이터프레임으로 저장합니다.
# sales.merge(products)
df = pd.merge(sales, products, on = 'ProductID')
df.head(3)

,OrderID,Seq,OrderDate,ProductID,Qty,Amt,CustomerID,ProductName,Category,SubCategory
0,107,2,2016-01-02,p1036481,2,2100,c150417,순두부,반찬류,두부
1,69,1,2016-01-02,p1152861,1,1091,c212716,포토아이스크림,유제품,아이스크림
2,69,7,2016-01-02,p1013161,1,2600,c212716,느타리버섯,채소,버섯

In [24]:
# 🤔2. Category 별 총 매출액(Amt)
df.groupby('Category', as_index=False)['Amt'].sum()

  Category       Amt
0       간식  12920570
1       과일  49789339
2      반찬류  32204820
3      유제품  45261956
4       채소  54822783

In [26]:
# 🤔3. Category 별 총 판매량(qty)
df.groupby('Category', as_index=False)['Qty'].sum()

  Category    Qty
0       간식  12130
1       과일   6786
2      반찬류  20210
3      유제품  19731
4       채소  27859

In [28]:
# 🤔4. 전체에서 가장 매출이 높은 상품명 10개 조회
df2 = df.groupby('ProductName', as_index=False)['Amt'].sum()  # 상품명별로 매출액 합계
df2.sort_values('Amt', ascending = False).head(10)

   ProductName       Amt
37      우유1000  18129067
23        사과_소  14078818
9         딸기_대  11011541
7         두부_대  10119037
10        딸기_소   7517664
8         두부_소   7319963
49         콩나물   6971347
39       유기농우유   6437323
50         토마토   6291001
43          참외   5491030

* 정렬 : .sort_values : https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_values.html

## 5.결합 ② : 붙이기  concat()

In [30]:
# 🤔1. 위 실습 4-2,3번의 결과를 각각 dataframe으로 저장하시오.
df3 = df.groupby('Category', as_index=False)['Amt'].sum()
df4 = df.groupby('Category', as_index=False)['Qty'].sum()

* 옆으로 붙이기 concat(,  axis = 1)

* https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html

In [34]:
# 🤔2. 옆으로 붙이기 concat(, axis = 1)
pd.concat([df3, df4], axis=1)

  Category       Amt Category    Qty
0       간식  12920570       간식  12130
1       과일  49789339       과일   6786
2      반찬류  32204820      반찬류  20210
3      유제품  45261956      유제품  19731
4       채소  54822783       채소  27859

In [40]:
# 🤔3. 2016년 1월 판매데이터를 저장하시오.
df5 = sales.loc[sales['OrderDate'].between('2016-01-01', '2016-02-01', inclusive = 'left')]

# 2017년 1월 판매데이터를 저장하시오.
df6 = sales.loc[sales['OrderDate'].between('2017-01-01', '2017-02-01', inclusive = 'left')]

# 만든 것 열어보기
display(df5.head(3))
display(df6.head(3))
display(df5.tail(3))
display(df6.tail(3))

   OrderID  Seq   OrderDate ProductID  Qty   Amt CustomerID
0      107    2  2016-01-02  p1036481    2  2100    c150417
1       69    1  2016-01-02  p1152861    1  1091    c212716
2       69    7  2016-01-02  p1013161    1  2600    c212716

       OrderID  Seq   OrderDate ProductID  Qty   Amt CustomerID
55976        5    2  2017-01-02  p1133371    7  7000    c271068
55977        5    6  2017-01-02  p1012751    1  1850    c271068
55978        5   10  2017-01-02  p1144661    1  1950    c271068

      OrderID  Seq   OrderDate ProductID  Qty   Amt CustomerID
4496      137    6  2016-01-31  p1001771    1  3300    c305733
4497      141    2  2016-01-31  p1072601    1  4150    c328823
4498      141    5  2016-01-31  p1201601    1  2870    c328823

       OrderID  Seq   OrderDate ProductID  Qty   Amt CustomerID
60651      105   26  2017-01-31  p1100371    5  1600    c217725
60652      107    1  2017-01-31  p1207281    1  3300    c234291
60653      107    2  2017-01-31  p1100371    1   400    c234291

In [44]:
# 두 데이터를 위/아래로 붙이시오.
df7 = pd.concat([df5, df6], axis = 0)
df7

       OrderID  Seq   OrderDate ProductID  Qty   Amt CustomerID
0          107    2  2016-01-02  p1036481    2  2100    c150417
1           69    1  2016-01-02  p1152861    1  1091    c212716
2           69    7  2016-01-02  p1013161    1  2600    c212716
3           69    8  2016-01-02  p1005771    1  1650    c212716
4           69   11  2016-01-02  p1089531    1  2600    c212716
...        ...  ...         ...       ...  ...   ...        ...
60649      105   19  2017-01-31  p1089531    1  2500    c217725
60650      105   24  2017-01-31  p1133371    2  2000    c217725
60651      105   26  2017-01-31  p1100371    5  1600    c217725
60652      107    1  2017-01-31  p1207281    1  3300    c234291
60653      107    2  2017-01-31  p1100371    1   400    c234291

[9177 rows x 7 columns]

## 6.시계열 데이터 다루기
rolling은 주로 시계열 데이터에 대해서 이동평균값을 구하거나, 행을 shift(이동) 시킬 때 주로 사용합니다.
> 시계열 데이터 : 행과 행에 시간순서가 있는 데이터(전제 : 시간순으로 정렬 되어 있는 상태)

* .shift() : https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.shift.html
* .rolling : https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rolling.html

In [46]:
!pip install pykrx

Collecting pykrx
  Downloading pykrx-1.0.48-py3-none-any.whl.metadata (60 kB)
     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.9 kB ? eta -:--:--
     ------------------------------- ------ 51.2/60.9 kB 525.1 kB/s eta 0:00:01
     -------------------------------------- 60.9/60.9 kB 539.2 kB/s eta 0:00:00
Requirement already satisfied: requests in c:\users\user\anaconda3\lib\site-packages (from pykrx) (2.32.2)
Requirement already satisfied: pandas in c:\users\user\anaconda3\lib\site-packages (from pykrx) (2.2.2)
Collecting datetime (from pykrx)
  Downloading DateTime-5.5-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: numpy in c:\users\user\anaconda3\lib\site-packages (from pykrx) (1.26.4)
Collecting xlrd (from pykrx)
  Downloading xlrd-2.0.1-py2.py3-none-any.whl.metadata (3.4 kB)
Collecting deprecated (from pykrx)
  Downloading Deprecated-1.2.14-py2.py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: multipledispatch in c:\users\user\anaconda3\lib\site-packages (from pykrx) (0.6.0)
Requirement already satisfied: matplotlib in c:\users\user\anaconda3\lib\site-packages (from pykrx) (3.8.4)
Requirement already satisfied: zope.interface in c:\users\user\anaconda3\lib\site-packages (from datetime->pykrx) (5.4.0)
Requirement already satisfied: pytz in c:\users\user\anaconda3\lib\site-packages (from datetime->pykrx) (2024.1)
Requirement already satisfied: wrapt<2,>=1.10 in c:\users\user\anaconda3\lib\site-packages (from deprecated->pykrx) (1.14.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->pykrx) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->pykrx) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->pykrx) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->pykrx) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->pykrx) (23.2)
Requirement already satisfied: pillow>=8 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->pykrx) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->pykrx) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->pykrx) (2.9.0.post0)
Requirement already satisfied: six in c:\users\user\anaconda3\lib\site-packages (from multipledispatch->pykrx) (1.16.0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\anaconda3\lib\site-packages (from pandas->pykrx) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\user\anaconda3\lib\site-packages (from requests->pykrx) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\anaconda3\lib\site-packages (from requests->pykrx) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\user\anaconda3\lib\site-packages (from requests->pykrx) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\anaconda3\lib\site-packages (from requests->pykrx) (2024.7.4)
Requirement already satisfied: setuptools in c:\users\user\anaconda3\lib\site-packages (from zope.interface->datetime->pykrx) (69.5.1)
Downloading pykrx-1.0.48-py3-none-any.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.2 MB 6.5 MB/s eta 0:00:01
   ----------------- ---------------------- 0.9/2.2 MB 9.9 MB/s eta 0:00:01
   -------------------------- ------------- 1.4/2.2 MB 10.1 MB/s eta 0:00:01
   ----------------------------------- ---- 1.9/2.2 MB 10.2 MB/s eta 0:00:01
   ---------------------------------------- 2.2/2.2 MB 9.9 MB/s eta 0:00:00
Downloading DateTime-5.5-py3-none-any.whl (52 kB)
   ---------------------------------------- 0.0/52.6 kB ? eta -:--:--
   ---------------------------------------- 52.6/52.6 kB ? eta 0:00:00
Downloading Deprecated-1.2.14-py2.py3-none-any.whl (9.6 kB)
Downloading xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
   ---------------------------------------- 0.0/96.5 kB ? eta -:--:--
   ---------------------------------------- 96.5/96.5 kB 5.4 MB/s eta 0:00:00
Installing collected packages: xlrd, deprecated, datetime, pykrx
Successfully installed datetime-5.5 deprecated-1.2.14 pykrx-1.0.48 xlrd-2.0.1

In [50]:
from pykrx import stock
import datetime
import numpy as np

# 오늘 날짜 가져오기
today = datetime.datetime.now()

# 1년 전 날짜 계산
one_year_ago = today - datetime.timedelta(days=365)

# 주가 데이터 다운로드 및 간단한 처리
stock = stock.get_market_ohlcv_by_date(one_year_ago.strftime('%Y%m%d'), today.strftime('%Y%m%d'), "030200")
stock.reset_index(inplace = True)
stock = stock[['날짜', '종가', '거래량']]
stock.columns = ['Date', 'Close', 'Volume']
stock.head()

        Date  Close   Volume
0 2023-09-12  30800   926182
1 2023-09-13  31250  1272677
2 2023-09-14  32000  1049773
3 2023-09-15  32850  1117873
4 2023-09-18  32350   658295

In [54]:
# 🤔1. 전날, 전전날 주가 변수를 추가하시오. (.shift)
stock['Close_lag1'] = stock['Close'].shift(1)  # 전날
stock['Close_lag2'] = stock['Close'].shift(2)  # 전전날
stock.head()

        Date  Close   Volume  Close_lag1  Close_lag2
0 2023-09-12  30800   926182         NaN         NaN
1 2023-09-13  31250  1272677     30800.0         NaN
2 2023-09-14  32000  1049773     31250.0     30800.0
3 2023-09-15  32850  1117873     32000.0     31250.0
4 2023-09-18  32350   658295     32850.0     32000.0

In [58]:
# 🤔2. 전전날 대비 전날 주가 증감 변수 추가 (.diff)
stock['Close_diff'] = stock['Close_lag1'].diff()  # 전날 - 전전날
stock.head()

        Date  Close   Volume  Close_lag1  Close_lag2  Close_diff
0 2023-09-12  30800   926182         NaN         NaN         NaN
1 2023-09-13  31250  1272677     30800.0         NaN         NaN
2 2023-09-14  32000  1049773     31250.0     30800.0       450.0
3 2023-09-15  32850  1117873     32000.0     31250.0       750.0
4 2023-09-18  32350   658295     32850.0     32000.0       850.0

In [60]:
# 🤔3. 2번 변수가 + 이면 1, 아니면 0 (np.where)
stock['Diff'] = np.where(stock['Close_diff'] > 0, 1, 0)
stock.head()

        Date  Close   Volume  Close_lag1  Close_lag2  Close_diff  Diff
0 2023-09-12  30800   926182         NaN         NaN         NaN     0
1 2023-09-13  31250  1272677     30800.0         NaN         NaN     0
2 2023-09-14  32000  1049773     31250.0     30800.0       450.0     1
3 2023-09-15  32850  1117873     32000.0     31250.0       750.0     1
4 2023-09-18  32350   658295     32850.0     32000.0       850.0     1

In [64]:
# 🤔4. 3일 이동평균 주가 변수를 추가하시오.(rolling().mean())
stock['Close_MA3'] = stock['Close'].rolling(3, min_periods=1).mean()
stock.head()

,Date,Close,Volume,Close_lag1,Close_lag2,Close_diff,Diff,Close_MA3
0,2023-09-12,30800,926182,NaN,NaN,NaN,0,30800.000000
1,2023-09-13,31250,1272677,30800.0,NaN,NaN,0,31025.000000
2,2023-09-14,32000,1049773,31250.0,30800.0,450.0,1,31350.000000
3,2023-09-15,32850,1117873,32000.0,31250.0,750.0,1,32033.333333
4,2023-09-18,32350,658295,32850.0,32000.0,850.0,1,32400.000000